name: Release

on: push

jobs:
  release:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.6-0'
          micromamba-binary-path: ${{ runner.temp }}/bin/micromamba
          environment-file: conda_environment.yaml
          environment-name: copernicusmarine
          condarc-file: .condarc
          cache-environment: true
          post-cleanup: 'all'
          
      - name: Set VERSION environment variable
        id: version
        shell: micromamba-shell {0}
        run: echo "VERSION=1.0.11" >> $GITHUB_OUTPUT
  
      - name: Wait for Pypi version to be available
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: 'https://pypi.org/project/copernicusmarine/${{ steps.version.outputs.VERSION }}/'
          responseCode: '200'
          timeout: 60000
          interval: 5000
        
      - name: final
        run: echo "ok"